title: Celine Wang # your name (or website title) here
logo: /assets/img/Celine.jpeg # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, holding multiple certificates in data analysis and machine learning. 
  With a background in chemical research and education.
  Proficient in Mandarin and Japanese. 
  Detail orientated, embraces challenges and eager to learn new skills. 
  <br><br>
  Certificates:<br>
  - Data science and visualization boot camp (UCSD)<br>
  - Machine Learning Specialization (Deeplearning.AI)<br>
  - Intensive Multi-Cloud Computing (The Cloud Bootcamp)<br>
  - Data Analyst Professional Program (Task Impetus)<br>
  - LinkedIn Badges: Python, MySQL, MS Excel<br>
  <br><br>
  <a href="https://www.linkedin.com/in/cewrs/">View My LinkedIn Profile</a> 
  <br>
  <a href="https://github.com/CelineWW">View My GitHub Profile</a> 
  <br>
  <a href="https://public.tableau.com/app/profile/celine7593">View My Tableau Public</a> 
  
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
